### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by peterpernhofer** [cepthomas/ICSharpCode.TextEditor.V4#3]
the complete Microsoft.CodeAnalysis Libraries aren't working. Tons of errors, the Nuget packages are not available and partially complete confusing hardcoded in the project file => ???
a pitty!

**Comment by cepthomas** [comment]
This is very stale. I had meant to archive it but forgot, now it is. Performance was degrading quickly with each new feature. Take a look at this instead: https://github.com/icsharpcode/AvalonEdit.
